In [41]:
import numpy as np

In [42]:
# VECTOR OPERATIONS

In [43]:
u = np.array([2, 4, 5, 6])

In [44]:
2 * u

array([ 4,  8, 10, 12])

In [45]:
v = np.array([1, 0, 0, 2])

In [46]:
u + v

array([3, 4, 5, 8])

In [47]:
# Multiplying Vectors with Vectors

In [48]:
u * v

array([ 2,  0,  0, 12])

In [49]:
# MULTIPLICATION

In [55]:
v.shape[0]

4

In [59]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

In [60]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [61]:
# DOT Operator
u.dot(v) # multiply u with v

np.int64(14)

In [68]:
# Matrix - Vector
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [69]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [70]:
U.shape

(3, 4)

In [71]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [79]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [80]:
# Numpy function for computing the function above
U.dot(v)

array([14,  5,  5])

In [85]:
V = np.array([
        [1, 1, 2],
        [0, 0.5, 1],
        [0, 2, 1],
        [2, 1, 0],
])

In [86]:
# MATRIX - MATRIX MULTIPLICATION

In [87]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [88]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [89]:
# Compute the above function with numpy dot function
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [91]:
# IDENTITY MATRIX
# In numpy we use eye() function

I = np.eye(3)

In [93]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [94]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [97]:
# MATRIX INVERSE

Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [99]:
# TO COMPUTE THE INVERSE..
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [100]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])