In [5]:
# Import libraries Pandas and Numpy
import pandas as pd
import numpy as np

In [6]:
# Check pandas version
pd.__version__

'2.3.3'

In [7]:
# ONE DIMENSIONAL ARRAYS

In [8]:
# Ones array
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [9]:
# Zeros array
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [10]:
# Full array
np.full(20, 10.99)

array([10.99, 10.99, 10.99, 10.99, 10.99, 10.99, 10.99, 10.99, 10.99,
       10.99, 10.99, 10.99, 10.99, 10.99, 10.99, 10.99, 10.99, 10.99,
       10.99, 10.99])

In [11]:
# Python List
list = [1, 23, 3, 5, 8]

In [12]:
# Converting a list to an array
np.array(list)

array([ 1, 23,  3,  5,  8])

In [13]:
# Storing
a = np.array(list)

In [14]:
# Re-assigning variables
a[2] = 13

In [15]:
# caller
a
print(a)

[ 1 23 13  5  8]


In [16]:
# Arange function
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
# Linspase function
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
# MULTI-DIMENSIONAL ARRAYS

In [19]:
# Zeros = attribute, 5 = rows, 2 = columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
# List of lists
listOfLists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
# Converting list of lists to 2d array
np.array(listOfLists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# Accessing elements within the multi-array
n = np.array(listOfLists)

In [23]:
n[2, 2] = 99

In [24]:
# caller
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [25]:
# Accessing and re-assigning rows only
n[0] = [5, 2, 1995]

In [26]:
# Accessing and re-assigining columns only
# : = return all the rows
n[:, 2] = [2, 18, 2023]

In [27]:
n

array([[   5,    2,    2],
       [   4,    5,   18],
       [   7,    8, 2023]])

In [28]:
# Generating the same random numbers inside the array
np.random.seed(2)
# Random numbers inside the array
# 100 = numbers between 1 and 100
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [29]:
# Normal Distribution
np.random.seed(2)
# n = normal distribution
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
# Random Integers
np.random.seed(2) # fixed numbers
# n = normal distribution
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [31]:
# ELEMENT-WISE OPERATIONS

In [32]:
# Regual 1d array
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
# Adding 1 increment to all elements in the array
a + 1

array([1, 2, 3, 4, 5])

In [34]:
# Multiplying 1 to all elements in the array
a * 2

array([0, 2, 4, 6, 8])

In [35]:
# Subtracting 1 from all elements in the array
a - 1

array([-1,  0,  1,  2,  3])

In [36]:
# Dividing 1 from all elements in the array
a/1

array([0., 1., 2., 3., 4.])

In [37]:
# We can also chain all operations
(1 * 2 + (a-1)) ** 2

array([ 1,  4,  9, 16, 25])

In [38]:
# Combining arrays(You may add, subtract, multiply or divide)
b = (1 * 2 + (a-1)) ** 2
a + b

array([ 1,  5, 11, 19, 29])

In [39]:
# COMPARISON OPERATIONS

In [40]:
# If you compare you will get boolean values for results
a <= 0

array([ True, False, False, False, False])

In [41]:
b

array([ 1,  4,  9, 16, 25])

In [42]:
# Comparing different arrays
c = b - a
a > b

array([False, False, False, False, False])

In [43]:
c - 3
c[4] = 100

In [44]:
b

array([ 1,  4,  9, 16, 25])

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
# See what elements inside row or column is greater or less than the other array
a[a < c] # elements inside "a" array that are less than elements inside "b" array

array([0, 1, 2, 3, 4])

In [47]:
c[c > b] # elements inside "c" array are greater than elements inside "b" array

array([100])

In [48]:
# SUMMARIZING OPERATIONS

In [49]:
a

array([0, 1, 2, 3, 4])

In [51]:
# Add all elements together
a.sum()

np.int64(10)

In [53]:
# Compute average of the elements
a.mean()

np.float64(2.0)

In [54]:
# Compute standard deviations
a.std()

np.float64(1.4142135623730951)

In [56]:
c.min()

np.int64(1)

In [57]:
# These functions apply to multi-dimensional arrays too
# Checking minimum
n.min()

np.int64(2)

In [58]:
# Adding all elements to get total
n.sum()

np.int64(2074)

In [59]:
# Computing the average for the elements
n.mean()

np.float64(230.44444444444446)